### PR TITLE
chat with csv plot improvements

### LINKED ISSUE #40: chat with csv custom queries for plots
currently, the chat with CSV app can only plot columns, but it cannot plot custom transformations of columns, see: https://github.com/ploomber/doc/pull/32#issuecomment-1787122039

we can change the system prompt to teach the LLM that it can generate a jupysql snippet and then call `sqlplot`, then, it'd be capable of running stuff like:

```
create a boxplot of the observations whose sex is MALE
```

### PR DESCRIPTION
**Pull request by neelasha23**
Closes #40 

----
:books: Documentation preview :books:: https://ploomber-doc--44.org.readthedocs.build/en/44/

### CODE REVIEW

**Comment by neelasha23** [comment]
deployed here: https://round-night-3811.ploomberapp.io/
@edublancas

**Review by edublancas — CHANGES_REQUESTED** [review]
looks good, let's just modify the query examples to show that we can plot data transformations 

Examples:
- Simple query: show me the unique values of column {column name}
- Plot columns: create a histogram (or boxplot) of {column name}
- Plot transformations: crate a histogram of column {colum name} where {another column} is {some value}

**Comment by neelasha23** [comment]
> looks good, let's just modify the query examples to show that we can plot data transformations

Fixed : https://cool-river-9326.ploomberapp.io/

@edublancas

**Review by edublancas — APPROVED** [review]

**Comment by neelasha23** [comment]
Sure !

**Pull request merged**
