### PR TITLE
Add REST API example with plumber

### PR DESCRIPTION
**Pull request by ellieko**
Added example code in `examples/plumber/` for writing a RESTful API using Plumber and deploying it on Ploomber Cloud

examples/plumber/
- Dockerfile
- main.R
- plot.png
- rest_controller.R

The detailed explanation is written in ploomber.io.

----
📚 Documentation preview 📚: https://ploomber-doc--260.org.readthedocs.build/en/260/

### CODE REVIEW

**Comment by neelasha23** [comment]
@ellieko Please deploy the app to prod and share the app link here

**Review by bryannho — COMMENTED** [review]
@neelasha23 it's currently available here: https://white-rice-0081.ploomberapp.io/__docs__/#/
but @ellieko let us know if that changes

Tested the API and it looks good, but will test again once the changes are made that we requested in the blog PR.

Refer to the other demo app readme.md for tips on formatting, the main thing is the title and description should look like:

```md
# Title

Description

Any other instructions
```

**Comment by neelasha23** [comment]
have u deployed a new app with he updated model? @ellieko

**Comment by ellieko** [comment]
@neelasha23 yes! I just deployed it here: https://dry-queen-2196.ploomberapp.io/__docs__/
I'm working on the README.md file, and will push the updates soon!

**Comment by ellieko** [comment]
@neelasha23 @bryannho
I've updated the demo and it's now live at https://dry-queen-2196.ploomberapp.io/__docs__/. I've also added README.md which is a simplified version of the blog post. Please take a look and share your thoughts!

**Review by neelasha23 — APPROVED** [review]
lgtm!

**Pull request merged**
