### PR TITLE
Hyperdiv docs

### PR DESCRIPTION
**Pull request by mariusnita**
This PR adds:

* A Hyperdiv example app in `examples/docker/hyperdiv`
* A Hyperdiv deployment doc page in `doc/apps/hyperdiv.md`

----
📚 Documentation preview 📚: https://ploomber-doc--149.org.readthedocs.build/en/149/

### CODE REVIEW

**Review by edublancas — APPROVED** [review]

**Comment by edublancas** [comment]
awesome! @mariusnita! can we add a reference to this document from [your docs](https://docs.hyperdiv.io/introduction/overview)?

**Comment by mariusnita** [comment]
Thanks! Yes, I'll work on a deployment section in the docs.

**Comment by edublancas** [comment]
hey @mariusnita: any updates on including ploomber in hyperdiv's docs? I couldn't find anything, let me know if you need help, happy to open a PR

**Comment by mariusnita** [comment]
There's a link on the homepage, not yet in docs. I am revamping docs with a separate deploy section and will add a ref to ploomber in there.

**Comment by edublancas** [comment]
nice, I see the button, It looks cool!

sounds good, let me know if you need anything from me!

**Pull request merged**
