### PR TITLE
Customer Chatbot

### LINKED ISSUE #139: customer chatbot v2
we need to improve the existing demo to be [more capable](https://github.com/ploomber/doc/pull/90/files)

The existing demo was built with haystack, I'll leave it up to you @neelasha23 to determine if it's worth keeping haystack or go straight to vanilla OpenAI. The problem of using haystack is that it creates another layer of abstraction, and introduces a lot of dependencies like torch, which slow down deployment significantly.

Feel free to change the code as much as you want to simplify and speed things up. 

we want this new version to allow canceling orders.

```
User: hi, I'd like to cancel an order
*Assistant (detects that the user wants to perform the CANCEL action on an order, but it's missing the ORDER ID*
Assistant: Sounds like you want to cancel an order, please provide the order ID
User: XYZ
*Assistant validates that XYZ is a valid order ID*
*Assistant calls a function that determines if order XYZ can still be canceled according to the company's policy*
Assistant: Your order can still be canceled, please confirm that you want to cancel order XYZ
User: Yes
Assistant: your order has been canceled
```

There might be other scenarios to consider, so as a first step, let's agree on what the process is, you can write a process diagram with [mermaid](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-diagrams)

### PR DESCRIPTION
**Pull request by neelasha23**
Closes #139 

----
📚 Documentation preview 📚: https://ploomber-doc--157.org.readthedocs.build/en/157/

### CODE REVIEW

**Comment by neelasha23** [comment]
App deployed here: https://proud-leaf-7750.ploomberapp.io/app
@edublancas

**Comment by edublancas** [comment]
I used the app that you deployed to test, but it's gone (I guess it was deleted because you uploaded to your account)

use the pro account we're sharing so the apps are not deleted

**Comment by neelasha23** [comment]
Have [fixed](https://github.com/ploomber/doc/pull/157/commits/710954ae63f59aad25259036d5f5aa5c57a38ad1#diff-69adcc7c9603ec70c12a3b557a08e35b432bdc27354ddf105c0fe7edaec06906R168-R174) the bug. It was coming up because OpenAI was responding with. different JSON format after multiple invalid requests.

Screenshot 2024-03-21 at 10 29 42 PM


Latest app deployed here: https://throbbing-pond-7869.ploomberapp.io/app

You can find the valid OrderID and customeIDs here: https://archive.ics.uci.edu/dataset/352/online+retail

@edublancas

**Comment by edublancas** [comment]
looks good, just two things to simplify the experience:

1. set a default customer ID so users don't have to put it
2. explain why you have a today's date field
3. add some explanation of the overall functionality in the left bar: use the default customer ID and "today's date" as a an example to explain what to expect. e.g. "customer with ID {X} has orders {Y}, {Z}, with the default today's date {XYZ}, you can cancel {Y} but not {Z} because Z is >14 days old. Try modifying the date to {ABC} so you can see that you can now cancel {Z}

**Comment by neelasha23** [comment]
Added [description](https://github.com/ploomber/doc/pull/157/commits/fd78b189092d4898420ebcdb22a7086aa08399b1)

App deployed here: https://holy-mountain-5431.ploomberapp.io/app

@edublancas

**Comment by edublancas** [comment]
there's a lot of unnecessary details in the text please trim it. some observations

- don't put the full URL, you can add the link on top of some text: [like this](https://ploomber.io/)
- shorten sentences: "Input a valid CustomerID. An user is only allowed to cancel their own orders. Default CustomerID is 15574." can just be "Input CustomerID, default provided"

this text is hard to read:

```
Let's see an example: Customer ID 15574 has placed orders 556878 (15.6.2011), 539215 (16.12.2010) and 536796 (2.12.2010).
Since the default today's is 20.6.2011 it is possible to cancel order 556878, but not the rest of the orders since they are more than 14 days old.
In order to cancel order 539215 change today's date to some relevant date that is not more than 14 days from 16.12.2010 like 18.12.2010. Similarly for order ID 536796.
```

- the date format doesn't match the date field
- you need a to do a lot of re-reading to understand what works and what doesn't. a simple format can be

CustomerID 15574 has this orders (using 2011-06-20 as today's date):

1) 556878 (X days old, you can cancel this one)
2) 539215 (Y days old, you cannot cancel)
3) 536796 (Z days old, you cannot cancel)

To cancel 2), set X as the date. To cancel 3) try setting Y as the date

---

please be more careful of these details, when users open an example, they won't spend much time on it if they don't understand it. we have to ensure to communicate a clear message as fast as we can

**Comment by neelasha23** [comment]
Updated [description](https://github.com/ploomber/doc/pull/157/commits/237c21277c18e230ca3d68f14f53f9230cfef641)
New app deployed: https://black-poetry-5215.ploomberapp.io/app
@edublancas

**Review by edublancas — APPROVED** [review]

**Pull request merged**
