### PR TITLE
Demo - Arxiv Summarizer

### LINKED ISSUE #87: demo: arxiv summarizer
build a chat application that can summarize the latest papers for a given area

- to begin with, let's focus on computer science papers
- arxiv has some paper taxonomy,perhaps we can use it to select sub areas of CS (e.g., AI/ML)
- once the user selects an area  we can display the abstracts for the most recent papers
- we can produce a 1-2 sentence summary by passing the abstract through OpenAI
- then users can ask other questions like: please tell me more about paper X, or give me alink to download paper Y

some code to get started: [arxiv.ipynb.zip](https://github.com/ploomber/doc/files/14070420/arxiv.ipynb.zip)

### PR DESCRIPTION
**Pull request by bryannho**
- A RAG for Arxiv articles - using Arxiv, OpenAI, and no other RAG libraries
- Uses Solara for the chat interface. **Important: When running locally, make sure you're using `solara==1.25.0`**, there is an issue with the CSS for `1.26.0`

Closes #87 

----
📚 Documentation preview 📚: https://ploomber-doc--112.org.readthedocs.build/en/112/

### CODE REVIEW

**Comment by edublancas** [comment]
the question that retrieves the topic can go in two ways:

1. either the user is asking about a category that exists in the arxiv [taxonomy](https://arxiv.org/category_taxonomy)
2. it doesn't exist

since there are too many classifications, you can just pick a few from the taxonomy list.

to know which one to use, you can do something similar to what I did in the [news RAG](https://github.com/ploomber/doc/blob/6fabcdcd01dbd55a7c45ca4a5c90c2f44ef17ee0/examples/panel/rag-news/app.py#L26), I use the LLM as a topic classifier, this classifier would output either a taxonomy (e.g. cs.AI) or no taxonomy.

in the first case, we can use arxiv's API to fetch the papers for that taxonomy (as you're doing via `cat:ID`), in the second case, we can pass the terms to the API e.g., `large+language+models`.  this will allow the bot to answer about topics that do not exist in the taxonomy:

image

**Comment by edublancas** [comment]
also the summary feature doesn't appear to be working, it just prints the paper authors

image

image


also, it should be clear what kind of things this bot can do: fetch recent papers, summarize papers, get links to download papers (anything else?)

**Comment by edublancas** [comment]
let's make this a link so clicking on it opens a tab:

image

**Comment by bryannho** [comment]
@edublancas 
> the question that retrieves the topic can go in two ways:
> 1. either the user is asking about a category that exists in the arxiv [taxonomy](https://arxiv.org/category_taxonomy)
> 2. it doesn't exist

The demo uses the LLM as a topic classifier as it did before, but now if it can't find a category, it passes the user's search terms to the API. 

Also, users can now load a **new set of articles** midway through the conversation as we discussed.

> also the summary feature doesn't appear to be working, it just prints the paper authors

Fixed the summary feature [here](https://github.com/ploomber/doc/pull/112/files#diff-5a8060509cc558bf54cce8e3c4b7577e4077716606f0b422bc628e53dd8f5bdcR188-R193). It grabs the summary verbatim from the Arxiv result.

> also, it should be clear what kind of things this bot can do: fetch recent papers, summarize papers, get links to download papers (anything else?)

I clarified the [initial prompt message](https://github.com/ploomber/doc/pull/112/files#diff-49432a7a2b00a8331fbc70d1b1260f029d1295b573866edf853f185ba1250b50R64-R68) to specify what the model can do. Let me know if this is descriptive enough.

> let's make this a link so clicking on it opens a tab

Download links are now clickable and will open in a new tab.

The updated version of the demo is deployed at: https://summer-wind-5194.ploomberapp.io/

**Review by edublancas — APPROVED** [review]

**Pull request merged**
