### PR TITLE
ocr solara app

### PR DESCRIPTION
**Pull request by neelasha23**
----
:books: Documentation preview :books:: https://ploomber-doc--34.org.readthedocs.build/en/34/

### CODE REVIEW

**Comment by edublancas** [comment]
a user reported the same issue when adding pytorch as a dependency to the image, I believe this is a similar issue. I need to spend some time investigating. let's pause this for now

**Comment by edublancas** [comment]
I believe there are still a few issues you can work on, right?

**Comment by edublancas** [comment]
@neelasha23 good news. I was able to fix this:

image


I'll open a PR to cloud repository, and we'll release this tomorrow

**Comment by neelasha23** [comment]
Yes I have other issues. Please provide feedback on the OCR app so that I can work on it too @edublancas

**Comment by edublancas** [comment]
the app looks good. I'd only change the text:

> This Solara app is designed for extracting text from images

for

> This app can extract text from images. Drop an image in the box to the left to get started or click on "Sample image"


the app is here btw: https://royal-rain-7673.dev.ploomberapp.io/ - you might wanna test

note that it'll be deleted in a few hours by our CI since this is in the dev environment

**Comment by neelasha23** [comment]
I have made the suggested changes. Please review @edublancas

**Review by edublancas — APPROVED** [review]

**Comment by edublancas** [comment]
great! We'll deploy this to showcase it once the fix for the docker step is in

**Pull request merged**
