### PR TITLE
Mosaic example

### LINKED ISSUE #16: better mosaic example
I added a voila + mosaic example here: https://github.com/ploomber/doc/tree/main/examples/voila/mosaic

but it's pretty basic, we need to update it so it's more impressive

a few thoughts:

- there is a JS example that uses 10M flights, let's see if we can use that dataset: https://observablehq.com/@uwdata/mosaic-cross-filter-flights-10m another example: https://uwdata.github.io/mosaic/examples/flights-10m.html
- the current example uses pandas, we should use duckdb instead since it'll allow us to analyze large datasets with less memory (by performing out of code aggreations)

relevant links:

- https://github.com/uwdata/mosaic
- https://uwdata.github.io/mosaic/what-is-mosaic/

### PR DESCRIPTION
**Pull request by neelasha23**
Closes #16 

----
:books: Documentation preview :books:: https://ploomber-doc--22.org.readthedocs.build/en/22/

### CODE REVIEW

**Comment by neelasha23** [comment]
I'm able to run this notebook on colab, but when uploaded to Ploomber cloud it throws error `There was an error when executing cell [2]. Please run Voilà with --show_tracebacks=True or --debug to see the error message, or configure VoilaConfiguration.show_tracebacks.` . How to check the stack trace?

Dashboard link: https://nameless-firefly-6621.ploomberapp.io/

@edublancas

**Comment by edublancas** [comment]
do the webservice logs show anything? 

image

**Comment by edublancas** [comment]
this is the error:

```
[Voila] ERROR | Error at server while executing cell: {'cell_type': 'code', 'source': '# We need to install httpfs to avoid error: httpfs.duckdb_extension not found\n\n%%sql duckdb://\nINSTALL httpfs', 'metadata': {'colab': {'base_uri': 'https://localhost:8080/', 'height': 58}, 'id': 'wpJIokxlckbD', 'outputId': '782bac11-c048-40f7-9d7d-58ea07018c24', 'trusted': False, 'execution': {'iopub.status.busy': '2023-10-06T16:47:27.524631Z', 'iopub.execute_input': '2023-10-06T16:47:27.525212Z', 'shell.execute_reply': '2023-10-06T16:47:27.530047Z', 'iopub.status.idle': '2023-10-06T16:47:27.530915Z'}}, 'execution_count': 2, 'outputs': [{'output_type': 'error', 'ename': 'SyntaxError', 'evalue': 'invalid syntax (4170849807.py, line 4)', 'traceback': ['\x1b[0;36m Cell \x1b[0;32mIn[2], line 4\x1b[0;36m\x1b[0m\n\x1b[0;31m INSTALL httpfs\x1b[0m\n\x1b[0m ^\x1b[0m\n\x1b[0;31mSyntaxError\x1b[0m\x1b[0;31m:\x1b[0m invalid syntax\n']}]}
```

but let me know if the logs don't show up. if that's the case, we have to fix it

**Comment by neelasha23** [comment]
Yes this is showing in logs. It's complaining of syntax error in the cell:
```
# We need to install httpfs to avoid error: httpfs.duckdb_extension not found 

%%sql duckdb://
INSTALL httpfs
```

Not sure why since it's running fine on colab. I'll recheck

**Comment by neelasha23** [comment]
The issue was happening due a comment. Fixed and redeployed: https://lively-fire-8614.ploomberapp.io/
Please review @edublancas

**Comment by edublancas** [comment]
nice! The visualization looks fine but it needs more context:

- some header (also include a "hosted in ploomber cloud" link)
- describe the dataset
- describe what each plot is
- how do use it (how do interact with the plots)

**Review by edublancas — APPROVED** [review]

**Pull request merged**
